version: '2'
services:
  logic:
    build: ./logic
    depends_on: 
       - filler
       - charger

  filler:
    build: ./filler
    depends_on:
      - logic
  charger:
    build: ./charger

  interface:
    build: ./interface
    depends_on:
      - logic
    ports:
      - "8080:8080"
