version: '2'
services:
  logic:
    image: registry.dockerization.xyz/dc/logic:latest
    depends_on:
       - filler
       - charger
    networks:
      - backend
      
  filler:
    image: registry.dockerization.xyz/dc/filler:latest
    networks:
      - backend

  charger:
    image: registry.dockerization.xyz/dc/charger:latest
    networks:
      - backend

  interface:
    image: registry.dockerization.xyz/dc/interface:latest
    depends_on:
      - logic
    ports:
      - "8080:8080"
    networks:
      - backend
      - web
networks:
  backend:
    driver: bridge
  web:
    driver: bridge
