version: '2'
services:
  logic:







  filler:
    build: ./filler
    depends_on:
      - logic



  charger:







  interface:
    build: ./interface
    depends_on:
      - logic
    ports:
      - "8080:8080"
